#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<EOSQL
CREATE USER ${MM_PROD_DB_USER} WITH PASSWORD '${MM_PROD_DB_PASSWORD}';
CREATE DATABASE ${MM_PROD_DB_NAME} OWNER ${MM_PROD_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${MM_PROD_DB_NAME} TO ${MM_PROD_DB_USER};

CREATE USER ${MM_TEST_DB_USER} WITH PASSWORD '${MM_TEST_DB_PASSWORD}';
CREATE DATABASE ${MM_TEST_DB_NAME} OWNER ${MM_TEST_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${MM_TEST_DB_NAME} TO ${MM_TEST_DB_USER};
EOSQL
