#!/usr/bin/env bash
set -euo pipefail

TOFU_DIR=${TOFU_DIR:-infra/opentofu}
OUTPUT_FILE=${OUTPUT_FILE:-}
SECRETS_FILE=${SECRETS_FILE:-.mattermost-secrets.env}
ENV_OUT=${ENV_OUT:-generated.env}
MM_VERSION=${MM_VERSION:-11.8.2}
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-mattermost}
LOCAL_BACKUP_RETENTION_DAYS=${LOCAL_BACKUP_RETENTION_DAYS:-7}
MM_FILESETTINGS_MAXFILESIZE=${MM_FILESETTINGS_MAXFILESIZE:-52428800}

json_get() {
  key=$1
  file=$2
  python3 - "$key" "$file" <<'PY'
import json
import sys

key, path = sys.argv[1], sys.argv[2]
with open(path, "r", encoding="utf-8") as fh:
    data = json.load(fh)
value = data.get(key, {}).get("value", "")
print(value if value is not None else "")
PY
}

random_hex() {
  openssl rand -hex 24
}

write_secrets_file() {
  umask 077
  cat > "$SECRETS_FILE" <<EOF
POSTGRES_SUPER_PASSWORD=$POSTGRES_SUPER_PASSWORD
MM_PROD_DB_PASSWORD=$MM_PROD_DB_PASSWORD
MM_TEST_DB_PASSWORD=$MM_TEST_DB_PASSWORD
MM_FILESETTINGS_AMAZONS3ACCESSKEYID=$MM_FILESETTINGS_AMAZONS3ACCESSKEYID
MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY=$MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY
EOF
}

if [ -z "$OUTPUT_FILE" ] && command -v tofu >/dev/null 2>&1 && [ -d "$TOFU_DIR" ]; then
  OUTPUT_FILE=$(mktemp)
  tofu -chdir="$TOFU_DIR" output -json > "$OUTPUT_FILE"
fi

if [ -n "$OUTPUT_FILE" ] && [ -f "$OUTPUT_FILE" ]; then
  PROD_HOSTNAME=${PROD_HOSTNAME:-$(json_get prod_hostname "$OUTPUT_FILE")}
  TEST_HOSTNAME=${TEST_HOSTNAME:-$(json_get test_hostname "$OUTPUT_FILE")}
  BACKUP_BUCKET_NAME=${BACKUP_BUCKET_NAME:-$(json_get backup_bucket_name "$OUTPUT_FILE")}
  CALLS_ICE_HOST_OVERRIDE=${CALLS_ICE_HOST_OVERRIDE:-$(json_get prod_hostname "$OUTPUT_FILE")}
  MM_FILESETTINGS_AMAZONS3BUCKET=${MM_FILESETTINGS_AMAZONS3BUCKET:-$(json_get file_bucket_name "$OUTPUT_FILE")}
  MM_FILESETTINGS_AMAZONS3REGION=${MM_FILESETTINGS_AMAZONS3REGION:-$(json_get file_s3_region "$OUTPUT_FILE")}
  OBJECT_STORAGE_NAMESPACE=${OBJECT_STORAGE_NAMESPACE:-$(json_get object_storage_namespace "$OUTPUT_FILE")}
  COMPARTMENT_OCID=${COMPARTMENT_OCID:-$(json_get compartment_ocid "$OUTPUT_FILE")}
fi

if [ -f "$SECRETS_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  source "$SECRETS_FILE"
  set +a
fi

POSTGRES_SUPER_PASSWORD=${POSTGRES_SUPER_PASSWORD:-$(random_hex)}
MM_PROD_DB_PASSWORD=${MM_PROD_DB_PASSWORD:-$(random_hex)}
MM_TEST_DB_PASSWORD=${MM_TEST_DB_PASSWORD:-$(random_hex)}
# Local-only credentials for the on-VM rclone S3 proxy.
MM_FILESETTINGS_AMAZONS3ACCESSKEYID=${MM_FILESETTINGS_AMAZONS3ACCESSKEYID:-$(random_hex)}
MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY=${MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY:-$(random_hex)}

: "${PROD_HOSTNAME:?Set PROD_HOSTNAME or provide OpenTofu outputs.}"
: "${TEST_HOSTNAME:?Set TEST_HOSTNAME or provide OpenTofu outputs.}"
: "${TEST_ALLOWED_CIDR:?Set TEST_ALLOWED_CIDR to the admin public IP/CIDR.}"
: "${MM_FILESETTINGS_AMAZONS3BUCKET:?Set MM_FILESETTINGS_AMAZONS3BUCKET or provide OpenTofu outputs.}"
: "${MM_FILESETTINGS_AMAZONS3REGION:?Set MM_FILESETTINGS_AMAZONS3REGION or provide OpenTofu outputs.}"
: "${OBJECT_STORAGE_NAMESPACE:?Set OBJECT_STORAGE_NAMESPACE or provide OpenTofu outputs.}"
: "${COMPARTMENT_OCID:?Set COMPARTMENT_OCID or provide OpenTofu outputs.}"

write_secrets_file

BACKUP_BUCKET_NAME=${BACKUP_BUCKET_NAME:-mattermost-backups}
MM_PROD_DB_NAME=${MM_PROD_DB_NAME:-mattermost_prod}
MM_PROD_DB_USER=${MM_PROD_DB_USER:-mattermost_prod}
MM_TEST_DB_NAME=${MM_TEST_DB_NAME:-mattermost_test}
MM_TEST_DB_USER=${MM_TEST_DB_USER:-mattermost_test}
CALLS_ICE_HOST_OVERRIDE=${CALLS_ICE_HOST_OVERRIDE:-$PROD_HOSTNAME}
# Mattermost → Compose service filestore-s3 (rclone) → OCI mattermost-files via instance principal.
MM_FILESETTINGS_AMAZONS3ENDPOINT=${MM_FILESETTINGS_AMAZONS3ENDPOINT:-filestore-s3:9000}
MM_FILESETTINGS_AMAZONS3SSL=${MM_FILESETTINGS_AMAZONS3SSL:-false}

umask 077
cat > "$ENV_OUT" <<EOF
MM_VERSION=$MM_VERSION
MM_TARBALL_SHA256=${MM_TARBALL_SHA256:-}
COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME

PROD_HOSTNAME=$PROD_HOSTNAME
TEST_HOSTNAME=$TEST_HOSTNAME
TEST_ALLOWED_CIDR=$TEST_ALLOWED_CIDR

POSTGRES_SUPER_PASSWORD=$POSTGRES_SUPER_PASSWORD

MM_PROD_DB_NAME=$MM_PROD_DB_NAME
MM_PROD_DB_USER=$MM_PROD_DB_USER
MM_PROD_DB_PASSWORD=$MM_PROD_DB_PASSWORD

MM_TEST_DB_NAME=$MM_TEST_DB_NAME
MM_TEST_DB_USER=$MM_TEST_DB_USER
MM_TEST_DB_PASSWORD=$MM_TEST_DB_PASSWORD

BACKUP_BUCKET_NAME=$BACKUP_BUCKET_NAME
LOCAL_BACKUP_RETENTION_DAYS=$LOCAL_BACKUP_RETENTION_DAYS

OBJECT_STORAGE_NAMESPACE=$OBJECT_STORAGE_NAMESPACE
COMPARTMENT_OCID=$COMPARTMENT_OCID

MM_FILESETTINGS_DRIVERNAME=amazons3
MM_FILESETTINGS_MAXFILESIZE=$MM_FILESETTINGS_MAXFILESIZE
MM_FILESETTINGS_ENABLEFILEATTACHMENTS=true
MM_FILESETTINGS_AMAZONS3BUCKET=$MM_FILESETTINGS_AMAZONS3BUCKET
MM_FILESETTINGS_AMAZONS3ENDPOINT=$MM_FILESETTINGS_AMAZONS3ENDPOINT
MM_FILESETTINGS_AMAZONS3REGION=$MM_FILESETTINGS_AMAZONS3REGION
MM_FILESETTINGS_AMAZONS3ACCESSKEYID=$MM_FILESETTINGS_AMAZONS3ACCESSKEYID
MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY=$MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY
MM_FILESETTINGS_AMAZONS3SSL=$MM_FILESETTINGS_AMAZONS3SSL
MM_FILESETTINGS_AMAZONS3SSE=false

MM_CALLS_UDP_SERVER_ADDRESS=0.0.0.0
MM_CALLS_UDP_SERVER_PORT=8443
MM_CALLS_ICE_HOST_OVERRIDE=$CALLS_ICE_HOST_OVERRIDE
EOF

if [ -n "${ALERT_WEBHOOK_URL:-}" ]; then
  printf 'ALERT_WEBHOOK_URL=%s\n' "$ALERT_WEBHOOK_URL" >> "$ENV_OUT"
fi

echo "Rendered $ENV_OUT"
echo "Stored generated secrets in $SECRETS_FILE"
